### ISSUE TITLE
Question: Why did you choose to use "CSGMesh3D" instead of a standard "MeshInstance3D" for the player entity?

### ISSUE THREAD

**Issue by BurntAussieTyre** [TechnoLukas/Godot4-Basic3dStarter#1]
Question: Why did you choose to use "CSGMesh3D" instead of a standard "MeshInstance3D" for the player entity?

**Comment by TechnoLukas** [comment]
Hi. For me it was more comfortable. + I thought it would be more easier for the user to understand that i use same objects for the environment and for the player.
